### ISSUE TITLE
Training 3D CNN on residue deletion

### ISSUE THREAD

**Issue by meghana-kshirsagar** [drorlab/atom3d#10]
Thanks for your really cool work and sharing the repository - your neurips paper's results looked very interesting. I am trying to retrain the 3dcnn model on the residue deletion task using the data splits that you have provided. After some changes to the code, I am stuck at the data loader. The data files you provide look like: 
```
data/residue_deletion/split/train_envs_0000_1000.h5
data/residue_deletion/split/train_envs_0001_1000.h5
```

Whereas the dataloader in `benchmarking/cnn3d/train_resdel.py`  currently expects the format in `ResDel_Dataset_PT` to be the following:
`        data = torch.load(os.path.join(self.path, f'data_t_{idx}.pt'))`

Can you please provide information on how to convert the h5 files to the format expected by the data loader? I looked at `atom3d/datasets/res/convert_resdel_from_hdf5_to_npz.py` but it doesn't look like the right conversion?

Any pointers to get the data loading to work would greatly help.

Thanks,
Meghana.

**Comment by awfderry** [comment]
Thank you for your interest in our work! We are currently in the process of refactoring the code and data to work with our new LMDB-based format, so some of the code in the benchmarking directory is still expecting the outdated format. Please stay tuned as we continue to work on this!

In the meantime, you can try using the `ResDel_Dataset` class rather than `ResDel_Dataset_PT`, which expects data to be already saved to disk locally.

**Comment by meghana-kshirsagar** [comment]
Thanks for your suggestion. I was able to get the `ResDel_Dataset_PT` based code running, but it takes forever (2 days) to generate the cube.pt files, especially for the training data (is this expected)? Is the number of shards = 1000? And there are hundreds of thousands of files (equal to number of residues in PDB)? Also, it expects a checkpoint model? `/CNN_3D_epoch_004_15000_weights.pt`

What are the pros / cons of the `ResDel_Dataset` class w.r.t `ResDel_Dataset_PT`? Is the latter faster w.r.t training?

In order to use [ResDel_Dataset](url), the code needs to be modified too as it doesn't work right now. Could you please check the current version to suggest quick fixes?

**Comment by meghana-kshirsagar** [comment]
Another question about . The shard files are named as:  
```
data_0_0.pt
data_0_1000.pt
data_0_1001.pt
```

but the training code only uses one id to retrieve a file and has a "`_t_`":
```
    def __getitem__(self, idx):
        data = torch.load(os.path.join(self.path, f'data_t_{idx}.pt'))
        label = torch.load(os.path.join(self.path, f'label_t_{idx}.pt'))
        return data, label
```

Can you please help figure out how to reconcile this?

**Comment by martinvoegele** [comment]
The shard format we used in previous versions is outdated. Sorry for the confusion!

Could you try using the LMDB dataset available here?
https://www.atom3d.ai/lba.html
We describe how to load it in the documentation:
https://atom3d.readthedocs.io/en/latest/using_datasets.html
