### ISSUE TITLE
Loading PPI Dataset with PyTorch Geometric

### ISSUE THREAD

**Issue by amorehead** [drorlab/atom3d#11]
Hello.

First off, I want to say that it is a sight for sore eyes seeing a repository as well documented as this. I am very impressed given the scope of it. 

On another note, I did encounter an odd ModuleNotFoundError when trying to the train_ppi.py script locally in the provided "geometric" Conda environment:

<frozen importlib._bootstrap>:665: in _load_unlocked
    ???
../../../../../anaconda3/envs/geometric/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
train_ppi.py:11: in <module>
    import ppi_dataloader as dl
ppi_dataloader.py:15: in <module>
    import atom3d.torch.graph as gr
E   ModuleNotFoundError: No module named 'atom3d.torch'

It appears as though a directory (atom3d.torch) did not get added to version control and, as such, is not appearing remotely. Was this omission intentional?

Thank you for your time!

**Comment by meghana-kshirsagar** [comment]
I think they refactored the directory structure and that has lead to many imports breaking. You can modify the above import to the following and it should work (it worked for me):

`import atom3d.util.graph as gr`

**Comment by amorehead** [comment]
Thank you for the suggestion!

**Comment by raphtown** [comment]
Hello to both of you!  Yes, we are still in the process of refactoring, though that is nearing its end and things should be pretty stable from here on out.   Meghana's suggestion is correct.
