### ISSUE TITLE
question on documentation

### ISSUE THREAD

**Issue by xinyuan-huang** [drorlab/atom3d#12]
Hi, on Example section of this page https://atom3d.readthedocs.io/en/latest/using_datasets.html

When demonstrating how to Extract all atoms within 5 Angstroms of a ligand,
you have following code
`
>>> lig_coords = fo.get_coordinates_from_df(atoms_df[atoms_df['subunit']=='LIG']) # get coords of ligand
>>> df_filtered = distance_filter(atoms_df, lig_coords, dist=5.0)`

But I find that the data type of subunit is int64, so this line of code looks wrong to me, is there something I missing?

Thanks in advance!

**Comment by awfderry** [comment]
Thanks for your interest! To clarify, the subunit field may be of any type; for some datasets it is `int` and for others it may be `str`. This example is meant to illustrate a case where the ligand is stored in a subunit called `LIG`, but in practice it could have a different label. Alternatively, the ligand could be stored in a separate atoms dataframe. I recommend checking out the specifications for the dataset you're using for your use case.

We will update the documentation to make this more clear, and we are in the process of updating/improving the dataset formats so stay tuned for that!
