### ISSUE TITLE
Identity30_splits for PDBBind

### ISSUE THREAD

**Issue by vsomnath** [drorlab/atom3d#14]
Hi, thank you for the efforts towards a common resource for structural biology benchmarks. I was currently working with the PDBBind dataset and wanted to test the model on the splits you provided. From the link for the dataset (https://www.atom3d.ai/lba.html), I was able to find the identity_60 splits, but could not find the identity_30 splits. 

Could you please link me to the same ?

**Comment by vsomnath** [comment]
The `train_identity30.txt` files under `splits/core` does not have the same size of splits as mentioned in the supplementary material of the ICLR submission.

**Comment by awfderry** [comment]
Hi, thanks for your interest in our work! We have just updated to a new version with LMDB format for both 30% and 60% splits of LBA. You should now be able to download both the processed datasets and the indices for each split at https://www.atom3d.ai/lba.html.
