### ISSUE TITLE
Dataset Preparation

### ISSUE THREAD

**Issue by popfido** [drorlab/atom3d#15]
If I wants to prepare a new dataset for LBA task, what should I do to deal with my data?

I prepared protein pdb files with corresponding ligand sdf files for this task.

And I see atom3d/atom3d/datasets/lba/process_pdbbind.py that generate three files of format (sdf, cif, cif). But in prepare_lmdb.py need file with formats: (sdf, pdb, pdb) correspondingly.

In my kind of view, I should first transform my dataset to generate (ligand, pocket, protein) fileset with `process_pdbbind.py` and then use `prepare_lmdb.py` to generate final hdf5 file for further loading by LMDBDataset. But it's clearly that now I cannot do in that way.

There also exists multiple scripts like `create_hdf5.py` that seems to be another way to generate hdf5 lmdb file.

So HOW should I do in depth to prepare?

I'm feeling super confusing on preparing new dataset and doing specific task with atom3d.

**Comment by awfderry** [comment]
Hi, thank you for your interest! With version 0.2.0, we have refactored all the datasets from HDF5 format to LMDB format. Please see the links on the website at https://www.atom3d.ai/lba.html to download the processed datasets. For documentation on working with the LMDB datasets, please see https://atom3d.readthedocs.io/en/latest/.

**Comment by Ahmadrezauf** [comment]
I was trying to make a lmdb file from an xyz file, but I keep receiving this error: 
  File "$DIR/python3.7/site-packages/Bio/PDB/Atom.py", line 96, in __init__
    assert not element or element == element.upper(), element
AssertionError: Si
But I assume that Si is a proper atom. How can I fix this issue?
