### ISSUE TITLE
Cannot find lmdb files in LBA dataset

### ISSUE THREAD

**Issue by Calvin-Qiu** [drorlab/atom3d#16]
I cannot find any lmdb files from the LBA dataset. I downloaded the dataset from the link posted [here](https://www.atom3d.ai/lba.html), and it only contained pdbbind_3dcnn.h5 and some txt files. I wonder how I can access the lmdb dataset.

**Comment by awfderry** [comment]
Hello, thanks for your interest! We just updated all links on the website to the new LMDB format, so the dataset should be available now at https://www.atom3d.ai/lba.html.
