### ISSUE TITLE
Guidance of running example

### ISSUE THREAD

**Issue by futianfan** [drorlab/atom3d#17]
Dear Authors, 

Thanks for your great works. 

I tried to use this repo. But I met some problems running example script. 

The first problem is how to create dataset from scratch.  For example, in README file, what is "PATH_TO_INPUT_DIR"? Should I download raw data and put it into PATH_TO_INPUT_DIR? Or it is already in the repo?  

Then, after I process the dataset, should I run "python data.py" & "python trian.py" in the ./example folder directly? 

Thanks in advance for your time!

**Comment by raphtown** [comment]
Thank you for your interest!  

You can download an ATOM3D dataset by following the instructions at https://atom3d.readthedocs.io/en/latest/using_datasets.html#downloading-lmdb-datasets.  You can create a new dataset by following https://atom3d.readthedocs.io/en/latest/creating_datasets.html. 

We are still building out the dataset-specific examples, but you can check out train.py https://github.com/drorlab/atom3d/tree/master/examples/smp/enn for an idea of how to approach this.

**Comment by futianfan** [comment]
Thanks for your quick response! I will try it.
