### ISSUE TITLE
how do i get processed data for ENN training

### ISSUE THREAD

**Issue by futianfan** [drorlab/atom3d#18]
Dear Authors, 

I met problems when preparing input for ENN training for SMP, as your example shows. Can you show the preprocessing script? I read your fantastic documentation. But I still need your help during preprocessing for ENN & SMP.

In addition, do you run "python train.py" directly in bash? 

Appreciate!

**Comment by martinvoegele** [comment]
Hi, fortunately we do not need to preprocess the dataset anymore.
I have added updated instructions here:
https://github.com/drorlab/atom3d/blob/master/examples/smp/enn/README.rst
Let us know how it goes.

**Comment by futianfan** [comment]
Will try it soon. Thanks!

**Comment by futianfan** [comment]
Hi, it works well! Thanks

**Comment by martinvoegele** [comment]
Great! Thanks for letting us know!
We are going to add more examples over the next few weeks.
