### ISSUE TITLE
example for LBA

### ISSUE THREAD

**Issue by futianfan** [drorlab/atom3d#19]
Dear Authors, 

I saw you provide examples for SMP, which is super helpful. I'm studying LBA and wonder how ENN models LBA, especially how ENN represents proteins. Will you release the example codes these days? Thanks

**Comment by martinvoegele** [comment]
Yes, I'm working on it. Will comment here when it's up.

**Comment by futianfan** [comment]
Look forward to seeing it!

**Comment by martinvoegele** [comment]
The LBA example is now up:
https://github.com/drorlab/atom3d/tree/master/examples/lba/enn
Please let us know how it works for you.

**Comment by futianfan** [comment]
Appreciate!

**Comment by martinvoegele** [comment]
I'm closing this. Feel free to open another issue if you run into a specific problem. All the best!

**Comment by Ahmadrezauf** [comment]
I think there is a problem with the inputs regarding the cgprod_bounded, cg_pow_normalization, cg_agg_normalization.
They are not properly parsed by the  train.py

**Comment by martinvoegele** [comment]
Thanks, you are right. For some parameters, the behavior we wanted to use for the paper is still hard-coded in `train.py`. I will change that soon and comment here again.

**Comment by martinvoegele** [comment]
Looks like we've already done that for LBA-ENN. So they are supposed to parse correctly. 
Could you point out the particular problem?

**Comment by Ahmadrezauf** [comment]
so first, by running the same given script in the lba example, I receive this error: "error: unrecognized arguments: --cgprod-bounded".
When --cgprod-bounded is removed from the input to train.py, there will be an error for the ENN_LBA function in train.py.
This is the case with all the cg-related inputs.

**Comment by martinvoegele** [comment]
Thanks, that's very helpful!
I do not get this error on my machine, so I think there are two things to try:

1. Make sure to install the latest version of Cormorant from the following repo:

        https://github.com/drorlab/cormorant.git

The version from `risilab` does not include the CG options.

2. Do you have the current version of ATOM3D (0.2.2) installed? If yes and it still does not work, you can try to uninstall atom3d and then install it from the repo (which has a few more things fixed than the latest PyPI release): 

        git clone https://github.com/drorlab/atom3d
        cd atom3d
        make requirements

I hope one of these things help.

**Comment by martinvoegele** [comment]
@raphtown, we should probably release 0.2.3 with the additions made since April.

**Comment by Ahmadrezauf** [comment]
Thanks a lot for the fast response. Installing coromorant from drorlab instead of risilab solved the problem!
