### ISSUE TITLE
Multiple sequences for one protein

### ISSUE THREAD

**Issue by Calvin-Qiu** [drorlab/atom3d#20]
I'm using the recently uploaded LBA dataset in LMDB format. I found that in many examples there is more than one string in the 'seq' attribute, which I understand to be the amino acids sequence of the protein in the complex. Can you explain why there can be multiple sequences for one protein?

**Comment by martinvoegele** [comment]
You are right. These are the amino acid sequences. 
Some structures contain more than one protein chain. The sequence of each chain included separately in the dataset.
