### ISSUE TITLE
Hyperparameters to reproduce the GCN performance on LBA

### ISSUE THREAD

**Issue by Calvin-Qiu** [drorlab/atom3d#21]
I'd like to know what batch size and the number of epochs were used to produce the result of GCN on LBA in the paper. In train_pdbbind.py, the batch size is set to 1 and the number of epochs is 100. However, the test RMSE I got using this setting more than ten times higher than the one reported in the paper.

**Comment by martinvoegele** [comment]
Thanks for letting us know! Have you checked whether the units match?

**Comment by Calvin-Qiu** [comment]
Yes, I believe the units match. Would you please share the hyperparameters(batch size, number of epochs) used to produce the results in the paper?

**Comment by awfderry** [comment]
Hi, please see the code in the examples folder (https://github.com/drorlab/atom3d/tree/master/examples/lba/gnn) for a reproducible training example using the LMDB format.
