### ISSUE TITLE
Missing atom3d.shard package in benchmarking/pytorch-geometric dataloaders.

### ISSUE THREAD

**Issue by swenson-nick** [drorlab/atom3d#23]
I was hoping to recreate the ppi benchmarking example for GNNs. It seems like the ppi_dataloader.py and most of the non QM9 data loaders import an atom3d.shard package which no longer exists. What is the best way to recreate the ppi experiment for GNNs?

Thank you!

**Comment by martinvoegele** [comment]
The shard module was indeed outdated and we have overhauled the datasets and loaders accordingly.
You can find an example training GNNs on PPI here: 
https://github.com/drorlab/atom3d/tree/master/examples/ppi/gnn
We describe the installation procedure for GNN training here:
https://atom3d.readthedocs.io/en/latest/training_models.html#gnn

I am closing this issue now as it refers to the outdated shard module. 
Feel free to open a new one if there are issues with the new example. Thanks!
