### ISSUE TITLE
Importing xyz file 

### ISSUE THREAD

**Issue by Ahmadrezauf** [drorlab/atom3d#25]
I was trying to make a lmdb file from an xyz file through atom3d.datasets, but I keep receiving this error:
File "$DIR/python3.7/site-packages/atom3d/util/formats.py", line 128, in df_to_bps
atom['element'])
File "$DIR/python3.7/site-packages/Bio/PDB/Atom.py", line 96, in init
assert not element or element == element.upper(), element
AssertionError: Si

The first line of my xyz file is: Si -0.04553300 -1.14436300 0.73426900
But I assume that Si is a proper element. How can I fix this issue?

**Comment by Ahmadrezauf** [comment]
Problem solved: apparently you have to have the name of the elements in the uppercase.

**Comment by martinvoegele** [comment]
Glad to see you figured it out. Thanks a lot for posting the solution!
