### ISSUE TITLE
Atom3D for a reaction dataset 

### ISSUE THREAD

**Issue by Ahmadrezauf** [drorlab/atom3d#26]
I was wondering if it is possible to use atom3D package to predict the properties of a reaction, where the input data could be the structure of the reactant and the product molecules, and the output is a property of the reaction itself.

**Comment by martinvoegele** [comment]
Yes, this should be possible. You can have a look at the LEP and MSP datasets and corresponding models for inspiration. In the dataset, you can create two atom dataframes - one for the reactants and one for the product. Then you can adapt one of the siamese-twin architecture models (or implement your very own ideas).
