### ISSUE TITLE
I met some difficulties when I installed your library and use it

### ISSUE THREAD

**Issue by xuzhang5788** [drorlab/atom3d#27]
First of all, thank you so much for your great repo!
1. Could you provide a tutorial for installations? When I followed your instructions, I found I have to install pyrr, torch-geometric.
2. I couldn't find atom3d.models.ff when I run from atom3d.models.ff import FeedForward
3. when I load dataset, using dataset = da.dataset('data/test_lmdb', 'lmdb', transform=tr.graph-transform), I got model 'atom3d.util.transforms' has no attribute 'graph_transform
4. which directory should I put the downloaded dataset into?
5. could you add reamde.rst into /examples/lba/cnn3d like /enn and /gnn?

I think you are changing dataload, there were some conflicts. If you would like to provide some demos, that will be a great help.
many thanks

**Comment by luwei0917** [comment]
1. make requirements will do.
2. I think they renamed it to MLP
3. it is now GraphTransform
4. anywhere I guess.
5. agree.

demo will be great.

**Comment by martinvoegele** [comment]
Hello and many thanks for your interest in ATOM3D!

Here the replies to (some of) your questions:
1. We have installation instructions on our documentation pages. 
    See here for general instructions: https://atom3d.readthedocs.io/en/latest/getting_started.html#installation
    To use GNNs or ENNs, you need some additional/different packages. This is described here: https://atom3d.readthedocs.io/en/latest/training_models.html#model-specific-installation-instructions
2. The former model FeedForward is now called MLP and you can import it via `from atom3d.models.mlp import MLP`. In general, I am going to update the example here: https://atom3d.readthedocs.io/en/latest/training_models.html#examples from which I assume you were getting these commands.
3. The former graph_transform is GraphTransform now. I will also update this in the example.
4. You can save the dataset wherever is convenient for you. Just provide the location as the first argument in `load_dataset`.
5. Maybe @psuriana can help with this.

Could you please specify the conflicts you experience with dataload? 
This would help us enormously in investigating them further.

So far, we have an example for loading datasets here: 
https://atom3d.readthedocs.io/en/latest/using_datasets.html#loading-datasets-in-python
We are always open to suggestions in case this leaves questions open.

**Comment by xuzhang5788** [comment]
Thank you so much for your reply.
When I ran the example of GNN at https://atom3d.readthedocs.io/en/latest/training_models.html, I got

<ipython-input-3-58dcaa0dea29> in <module>
      1 # get number of input features from first graph
----> 2 for batch in dataloader:
      3     graph = batch['atoms']
      4     in_dim = graph.num_features
      5     break

~/miniconda3/envs/geometric/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    519             if self._sampler_iter is None:
    520                 self._reset()
--> 521             data = self._next_data()
    522             self._num_yielded += 1
    523             if self._dataset_kind == _DatasetKind.Iterable and \

~/miniconda3/envs/geometric/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    559     def _next_data(self):
    560         index = self._next_index()  # may raise StopIteration
--> 561         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    562         if self._pin_memory:
    563             data = _utils.pin_memory.pin_memory(data)

~/miniconda3/envs/geometric/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

~/miniconda3/envs/geometric/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

~/miniconda3/envs/geometric/lib/python3.7/site-packages/atom3d/datasets/datasets.py in __getitem__(self, index)
    111             item['id'] = str(index)
    112         if self._transform:
--> 113             item = self._transform(item)
    114         return item
    115 

TypeError: __init__() missing 1 required positional argument: 'label_key'

**Comment by awfderry** [comment]
@xuzhang5788 thanks for sending your traceback. The GraphTransform object takes arguments for the names of the atom and label keys, see [here](https://github.com/drorlab/atom3d/tree/master/atom3d/data) for more details. So you can replace `tr.GraphTransform` with `tr.GraphTransform(atom_keys=['atoms'], label_key='label')`. The docs have also been updated accordingly.

**Comment by xuzhang5788** [comment]
@awfderry Thank you for your reply!
However, I made the change, it worked at the dataloading stage, but I ran

for batch in dataloader:
    graph = batch['atoms']
    in_dim = graph.num_features
    break

I got:
WARNING:root:Data types in item 0 not defined. Will use basic types only.

 TypeError: unhashable type: 'list' 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-58dcaa0dea29> in <module>
      1 # get number of input features from first graph
----> 2 for batch in dataloader:
      3     graph = batch['atoms']
      4     in_dim = graph.num_features
      5     break

~/miniconda3/envs/geometric/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    519             if self._sampler_iter is None:
    520                 self._reset()
--> 521             data = self._next_data()
    522             self._num_yielded += 1
    523             if self._dataset_kind == _DatasetKind.Iterable and \

~/miniconda3/envs/geometric/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    559     def _next_data(self):
    560         index = self._next_index()  # may raise StopIteration
--> 561         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    562         if self._pin_memory:
    563             data = _utils.pin_memory.pin_memory(data)

~/miniconda3/envs/geometric/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

~/miniconda3/envs/geometric/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

~/miniconda3/envs/geometric/lib/python3.7/site-packages/atom3d/datasets/datasets.py in __getitem__(self, index)
    111             item['id'] = str(index)
    112         if self._transform:
--> 113             item = self._transform(item)
    114         return item
    115 

~/miniconda3/envs/geometric/lib/python3.7/site-packages/atom3d/util/transforms.py in __call__(self, item)
      8     def __call__(self, item):
      9         # transform protein and/or pocket to PTG graphs
---> 10         item = prot_graph_transform(item, atom_keys=self.atom_keys, label_key=self.label_key)
     11 
     12         return item

~/miniconda3/envs/geometric/lib/python3.7/site-packages/atom3d/util/transforms.py in prot_graph_transform(item, atom_keys, label_key)
     42 
     43     for key in atom_keys:
---> 44         node_feats, edge_index, edge_feats, pos = gr.prot_df_to_graph(item[key])
     45         item[key] = Data(node_feats, edge_index, edge_feats, y=item[label_key], pos=pos)
     46 

~/miniconda3/envs/geometric/lib/python3.7/site-packages/atom3d/util/graph.py in prot_df_to_graph(df, feat_col, allowable_feats, edge_dist_cutoff)
     46     :rtype: Tuple
     47     """ 
---> 48     node_pos = torch.FloatTensor(df[['x', 'y', 'z']].to_numpy())
     49 
     50     kd_tree = ss.KDTree(node_pos)

TypeError: unhashable type: 'list'

**Comment by martinvoegele** [comment]
I've added a readme file to examples/lba/cnn3d:
https://github.com/drorlab/atom3d/blob/master/examples/lba/cnn3d/README.rst
Hope this helps.

**Comment by awfderry** [comment]
Hi @xuzhang5788, we have updated the test data and documentation and this issue should be fixed now. Please let us know if you have any further issues!
