### ISSUE TITLE
How to train the cnn model?

### ISSUE THREAD

**Issue by xuzhang5788** [drorlab/atom3d#29]
I used
python train.py 
--data_dir data/split-by-sequence-identity-30/data/ 
--mode train 
--batch_size 16 
--num_epochs 50 
--learning_rate 1e-4
(very similar to gnn and enn model training method)
but I got:

Traceback (most recent call last):
  File "train.py", line 173, in <module>
    parser.add_argument('--data_dir', type=str, default=os.environ['LBA_DATA'])
  File "/home/xzhang/miniconda3/envs/atom3d/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'LBA_DATA'

**Comment by martinvoegele** [comment]
The code of the 3DCNN models has a bit different options from the other ones. The three methods were built by adapting three different existing models. 

You can avoid the KeyError in `os.environ()` by pre-defining the variables in question. For example, define the directories:
```
export LOG_DIR=~/atom3d/examples/lba/cnn3d/log/
export LBA_DATA=~/atom3d-data/lba/
```
You can then check all the other options via the `--help` option:
```
python train.py --help
```
This provides the following (for me):

> usage: train.py [-h] [--data_dir DATA_DIR] [--mode {train,test}]
>                 [--output_dir OUTPUT_DIR] [--unobserved]
>                 [--learning_rate LEARNING_RATE]
>                 [--conv_drop_rate CONV_DROP_RATE]
>                 [--fc_drop_rate FC_DROP_RATE] [--num_epochs NUM_EPOCHS]
>                 [--num_conv NUM_CONV] [--batch_norm] [--no_dropout]
>                 [--batch_size BATCH_SIZE] [--random_seed RANDOM_SEED]
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   --data_dir DATA_DIR
>   --mode {train,test}
>   --output_dir OUTPUT_DIR
>   --unobserved
>   --learning_rate LEARNING_RATE
>   --conv_drop_rate CONV_DROP_RATE
>   --fc_drop_rate FC_DROP_RATE
>   --num_epochs NUM_EPOCHS
>   --num_conv NUM_CONV
>   --batch_norm
>   --no_dropout
>   --batch_size BATCH_SIZE
>   --random_seed RANDOM_SEED
>

**Comment by martinvoegele** [comment]
I am closing this issue. 
Feel free to re-open it if the above does not solve this error for you.
Please open a new issue if you run into another problem.
