### ISSUE TITLE
Error downloading LBA dataset

### ISSUE THREAD

**Issue by Wufang1997** [drorlab/atom3d#30]
Hi, I download and unzip the dataset from https://zenodo.org/record/4914718#.YPFQNegzZPY. However, I found no lmdb file since I want to use 'from atom3d.datasets import LMDBDataset
dataset = LMDBDataset(PATH_TO_LMDB)
print(len(dataset))  # Print length
print(dataset[0])  # Print 1st entry
labels = [item['scores']['neglog_aff'] for item in dataset] # Get all labels'. 

Can you give me guidance on how to load the LBA dataset correctly?

**Comment by martinvoegele** [comment]
Hi, thanks for your interest in our dataset!

Here is how you load it from the downloaded and unzipped folder - assuming you want to load the training data of _split-by-sequence-identity-30_ as an example:

    from atom3d.datasets import LMDBDataset
    dataset = LMDBDataset('split-by-sequence-identity-30/data/train')
    print(len(dataset)) # Print length
    print(dataset[0]) # Print 1st entry
    labels = [item['scores']['neglog_aff'] for item in dataset]

Not that, in general, there is not _one_ LMDB file but _two_ (`lock.mdb` and `data.mdb`) and you should provide _the path_ to them.

I hope this explanation helps.

**Comment by Wufang1997** [comment]
Thanks for your help!
