### ISSUE TITLE
how to specify the relative position?

### ISSUE THREAD

**Issue by futianfan** [drorlab/atom3d#33]
In PPI and LBA, how do you specify the coordinate of two 3d graph? e.g., 2 proteins, ligand and target.

**Comment by martinvoegele** [comment]
Hi Tianfan,
Thanks for your question! 
The coordinates are stored in pandas dataframes.

To read a dataset, run:

    from atom3d.datasets import LMDBDataset
    dataset = LMDBDataset(PATH_TO_LMDB)
    print(dataset[0])  # Print 1st entry

The coordinates can be accessed via the keys that contain `atoms`. If there are two different parts of a structure, there can be multiple such entries. For example, in LBA:

- `['atoms_protein']` (pandas.DataFrame) All atoms of the protein.
- `['atoms_pocket']` (pandas.DataFrame) Only the binding pocket (protein atoms within 6.0 Angstroms of any atom in the ligand).
- `['atoms_ligand']` (pandas.DataFrame) Atoms of the ligand.

You can access, e. g., the coordinates of the binding pocket of the first (0th) entry via

    coord_pocket = dataset[0]['atoms_pocket']
    coord_ligand = dataset[0]['atoms_ligand']

If you would like to use a combined system (e.g. pocket and ligand), you can just combine the two data frames to one.

    coord_combined = pd.concat([coord_pocket, coord_ligand])

I hope this is helpful.

**Comment by futianfan** [comment]
thanks, does the raw data has their 3d position?

**Comment by martinvoegele** [comment]
Yes, the 3D position is encoded in the columns named x, y and z.

**Comment by martinvoegele** [comment]
I'm closing this issue. 
Feel free to reopen it if anything has remained unclear or raise a new issue if something else comes up.
