### ISSUE TITLE
lba bugs

### ISSUE THREAD

**Issue by futianfan** [drorlab/atom3d#34]
When i use enn in lba, it seems "cgprod_bounded" is not defined in argsparse and got some errors. Thanks for your time!

**Comment by futianfan** [comment]
Dear Authors, I found several bugs related to the argument "cg*".  Thanks!

**Comment by martinvoegele** [comment]
Hi Tianfan, did you make sure to install Cormorant from the `drorlab` fork?
`https://github.com/drorlab/cormorant`
The original version from Risi Kondor's lab does not have these arguments.

**Comment by futianfan** [comment]
let me try it. thanks

**Comment by futianfan** [comment]
it works now. thanks
