### ISSUE TITLE
model.to(device)

### ISSUE THREAD

**Issue by futianfan** [drorlab/atom3d#37]
Dear Authors, 

I use the LBA model and try to use "model = model.to(device)", but it got the error

"device, dtype, non_blocking = torch._C._nn._parse_to(*args, **kwargs)
ValueError: too many values to unpack (expected 3)"

do you know how to change the device (e.g., cpu to gpu) for the CGModule model? 

thanks a lot!

**Comment by martinvoegele** [comment]
Hi, I think we might need a bit more information to help. Let's start with the following: 

- Which LBA model are you trying to run? 3DCNN, GNN or ENN? 
- What is the command that you use?
- In which line does the error occur?
- What is the full error message?
- Which version of PyTorch and CUDA are you using?

**Comment by martinvoegele** [comment]
This issue has been silent for a few months, so I'm closing it. Feel free to reopen it if the problem persists.
