### ISSUE TITLE
How to evaluate and tune each model?

### ISSUE THREAD

**Issue by xuzhang5788** [drorlab/atom3d#38]
Based on lba problems, for each model: cnn3d, enn, and gnn, how to tune the models if I use my own data? How can I evaluate the models and do predictions? If you can provide examples, that will be a great help. Many thanks

**Comment by martinvoegele** [comment]
Hi, we provide analysis code in the examples directories, e.g. here:
https://github.com/drorlab/atom3d/blob/master/examples/lba/enn/evaluate.py

This example makes use of some basic functions we provide [to load results](https://atom3d.readthedocs.io/en/latest/source/atom3d.util.html#module-atom3d.util.results) and [to calculate performance metrics](https://atom3d.readthedocs.io/en/latest/source/atom3d.util.html#module-atom3d.util.metrics).
