### ISSUE TITLE
LBA Dataset Confirmation

### ISSUE THREAD

**Issue by chao1224** [drorlab/atom3d#42]
Hi there,

Thank you for providing the code base. I have one question about LBA dataset.

After downloading, I found there are 4,463 datapoints under folder `pdbbind_2019-refined-set`, however, on the PDBBind website, it shows that `pdbbind_2018` version has the same number of datapoints. So I just want to double-check which version are you using?

**Comment by awfderry** [comment]
Thanks for your interest! We do use the 2019 refined set, and filter the data based on various criteria as specified in our paper (such as having valid ligands readable by RDKit), which reduces the number of datapoints. If this is the same number as PDBBind 2018, that is coincidental.
