### ISSUE TITLE
Can't execute create_hdf5.py

### ISSUE THREAD

**Issue by AllanSCosta** [drorlab/atom3d#5]
It seems we are trying to import from `util` instead of from `atom3d.util`:

```
Traceback (most recent call last):
  File "atom3d/datasets/lba/create_hdf5.py", line 11, in <module>
    from util import datatypes as dt
ImportError: cannot import name 'datatypes'
```
I changed the imports to:

```
import atom3d.util.formats as dt
import atom3d.util.file as fi
```

Thanks!
Allan

**Comment by martinvoegele** [comment]
Fixed it. Thanks for letting us know!

**Comment by AllanSCosta** [comment]
More generally, I'm still trying to understand the pipeline for processing PDBbind data: after executing `process_PDBbind.py`, I imagine the next one would be `create_hdf5.py`, or `get_labels.py`, correct? Unfortunately, neither seems to be set to process the output of `process_PDBbind`. If you prefer, we may communicate through other channels as well.

Thanks a lot!
