### ISSUE TITLE
Face No module named 'data_qm9_for_ptgeom' when training qm9

### ISSUE THREAD

**Issue by Wilson-ZHANG** [drorlab/atom3d#6]
As the README.md said, I executed and met some problem as follows.
The whole log is below,
(env) [ pytorch_geometric]$ python train_qm9.py --target 7 --prefix qm9-u0
Traceback (most recent call last):
  File "train_qm9.py", line 10, in <module>
    from data_qm9_for_ptgeom import GraphQM9
ModuleNotFoundError: No module named 'data_qm9_for_ptgeom'

**Comment by martinvoegele** [comment]
Thanks for pointing this out!
The QM9 data loader should be fixed now.
