### ISSUE TITLE
How to get the Ground Truth binding site ? What is the Distance Cutoff? 

### ISSUE THREAD

**Issue by aggelos-michael-papadopoulos** [drorlab/atom3d#65]
Supposing that we have 1a05.pdb. So chainA is the receptor chain and chainB is the ligand chain. How can we determine the binding site from chainA (receptor)?
What is the cutoff distance that the atoms from receptor chain must have from the antigen chain in order to find the binding site atoms that will form the binding site?

I know for Protein-Ligand tasks the threshold is 4 Armstrong, but i think they do not have a clear answer on Protein-Protein tasks. I have seen DB5.5 and DIPS datasets, but i still cannot figure out how they do get the ground truth binding site for each pair of proteins.

ps: I do also know that these atoms have to be on the Surface of the receptor, so first we have to create a 3D grid around the receptor's protein.

**Comment by martinvoegele** [comment]
For proteins, a cutoff of four ångströms (4 Å) would usually mean that you use all atoms of every residue that has at least one atom within 4 Å of the ligand.

**Comment by aggelos-michael-papadopoulos** [comment]
![2023-11-04 23_40_17-Window](https://github.com/drorlab/atom3d/assets/65830412/4c6be942-e422-4792-9987-3efd1880e2ad)
On the DIPS paper they are saying that for both DIPS dataset and DB5.5 they used a six ångströms (6 Å) threshold

**Comment by martinvoegele** [comment]
That's right, thanks!
