### ISSUE TITLE
Training GNN on PDBBind

### ISSUE THREAD

**Issue by bfabiandev** [drorlab/atom3d#7]
Hi, 

I was really intrigued by this work when I heard the presentation at NeurIPS and wanted to try setting it up by running the pytorch-geometric GNN on PDBBind, but wasn't able to due to various issues. Could you please add some documentation on how to download the dataset, how to generate splits and how to train a model? Various functions seemed to have been moved or renamed (maybe some tests would help to ensure this doesn't happen?). 

I think most of the pieces are there and this project has a lot of potential, so I'm looking forward to coming back to it.

**Comment by raphtown** [comment]
Hello,

Thank you for the interest!  Yes, we are still in the midst of adding some pieces of documentation/cleaning up the repository.  I would recommend checking back in in a couple of weeks.

Cheers!

**Comment by awfderry** [comment]
We have now put up code for training the GNN on the LBA dataset in the examples folder of the repo (https://github.com/drorlab/atom3d/tree/master/examples/lba/gnn). There is additional documentation on the data format, downloading datasets, and training at atom3d.readthedocs.io.

Thanks for your patience!
