### ISSUE TITLE
Loading LBA dataset.

### ISSUE THREAD

**Issue by rohskopf** [drorlab/atom3d#9]
I'd like to load the LBA dataset and get the following:

1. Amino acid sequences
2. SMILES strings for the molecules
3. Binding affinity values

I downloaded the LBA dataset and loaded it in python with:

```
# Load dataset from directory of PDB files
dataset = da.load_dataset("ligand_binding_affinity", 'pdb')
```

But how can I get the amino acid sequences, SMILES strings, and binding affinity from this?

Thanks for your time.

**Comment by psuriana** [comment]
Currently, the HDF version of the LBA dataset doesn't contain the AA seq and SMILES data. We are going to release an updated version of the dataset that includes those information pretty soon!

**Comment by ZackS13** [comment]
Hi Patricia, any updates to this issue? Thanks

**Comment by psuriana** [comment]
@ZackS13 Sorry for the delay. The updated LBA dataset has now been released. Now the dataset also contains the SMILES of the ligand and the AA seq of the protein. The dataset is in LMDB format. The instructions on how to load the dataset and what keys each item contains are included in the README. The ones relevant to you are probably the `smiles` and `seq`.
